### ISSUE TITLE
How to install grpc module?

### ISSUE THREAD

**Issue by acehko** [pubref/rules_node#53]
I am trying to install the grpc module. This is my `yarn_modules` rule:
```python
yarn_modules(
    name = "yarn_modules",
    deps = {
        "grpc": "1.8.0",
    },
)
```
and my `node_module`:
```python
node_module(
    name = "my_module",
    srcs = glob(["**/*.js"]),
    package_json = "package.json",
    deps = [
        "@yarn_modules//:_all_",
    ],
)
```

This is the output when trying to build:
```
bazel build //:my_module                                                              ~/code/node/test
ERROR: /home/andrija/code/node/test/BUILD.bazel:3:1: no such package '@yarn_modules//': Traceback (most recent call last):
        File "/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/org_pubref_rules_node/node/internal/yarn_modules.bzl", line 59
                execute(ctx, [node, yarn_js, "install"], qui..., ...)})
        File "/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/org_pubref_rules_node/node/internal/yarn_modules.bzl", line 4, in execute
                fail((" ".join(cmds) + ("failed: \nST...))))
/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/bin/node /home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn/bin/yarn.js installfailed:
STDOUT:
yarn install v1.0.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

STDERR:
warning package.json: No license field
warning yarn_modules@1.0.0: No license field
error /home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn_modules/node_modules/grpc: Command failed.
Exit code: 1
Command: ./node_modules/.bin/node-pre-gyp install --fallback-to-build --library=static_library
Arguments:
Directory: /home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn_modules/node_modules/grpc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@7.10.1 | linux | x64
node-pre-gyp info check checked for "/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn_modules/node_modules/grpc/src/node/extension_binary/node-v51-linux-x64-unknown/grpc_node.node" (not found)
node-pre-gyp http GET https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v51-linux-x64-unknown.tar.gz
node-pre-gyp http 403 https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v51-linux-x64-unknown.tar.gz
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v51-linux-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@7.10.1 (node-v51 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v51-linux-x64-unknown.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.10.1 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.10.1 | linux | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:368:16)
gyp ERR! stack     at F (/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:114:15)
gyp ERR! System Linux 4.14.10-1-ARCH
gyp ERR! command "/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/bin/node" "/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn_modules/node_modules/grpc/src/node/extension_binary/node-v51-linux-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn_modules/node_modules/grpc/src/node/extension_binary/node-v51-linux-x64-unknown"
gyp ERR! cwd /home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn_modules/node_modules/grpc
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/bin/node /home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn_modules/node_modules/grpc/src/node/extension_binary/node-v51-linux-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn_modules/node_modules/grpc/src/node/extension_binary/node-v51-linux-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn_modules/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.14.10-1-ARCH
node-pre-gyp ERR! command "/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/bin/node" "/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn_modules/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn_modules/node_modules/grpc
node-pre-gyp ERR! node -v v7.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/bin/node /home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn_modules/node_modules/grpc/src/node/extension_binary/node-v51-linux-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/home/andrija/.cache/bazel/_bazel_andrija/c7bb9f3942b5e0db06620b8d5aefb3b9/external/yarn_modules/node_modules/grpc/src/node/extension_binary/node-v51-linux-x64-unknown' (1)
 and referenced by '//:my_module'
ERROR: Analysis of target '//:my_module' failed; build aborted: Loading failed
INFO: Elapsed time: 9.505s
FAILED: Build did NOT complete successfully (0 packages loaded)
```
It seems that grpc depends on node-gyp, which requires python to build.
Is there any way this can be installed?

**Comment by pcj** [comment]
GRPC is a complex dependency.  AFAIK node-gyp has a hard dependency on python, so I think you'll have to have it installed.  Maybe grpc discuss has more information about the precompiled binaries.
