### ISSUE TITLE
Cannot build module "ref"

### ISSUE THREAD

**Issue by iphydf** [pubref/rules_node#59]
WORKSPACE:
```python
RULES_NODE_COMMIT = "cbff612b717b9a91b1c0375ae6b02e029e3d5273"

http_archive(
    name = "org_pubref_rules_node",
    sha256 = "cb3fa6b540133585426f283f3453cfe07309f0ccd437159a8dd7afbb88e71c52",
    strip_prefix = "rules_node-%s" % RULES_NODE_COMMIT,
    url = "https://github.com/pubref/rules_node/archive/%s.zip" % RULES_NODE_COMMIT,
)

load("@org_pubref_rules_node//node:rules.bzl", "node_repositories", "yarn_modules")

node_repositories()

yarn_modules(
    name = "js_toxcore_c_modules",
    #package_json = "//js-toxcore-c:package.json",
    deps = {"ref": "1.3.5"},
)
```

Command: `$ bazel build @js_toxcore_c_modules//...`

Error:
```
ERROR: Traceback (most recent call last):
        File "/usr/local/home/iphy/.cache/bazel/_bazel_iphy/87c462f2b35b8d3dfe6f6c21308fd127/external/org_pubref_rules_node/node/internal/yarn_modules.bzl", line 59
                execute(ctx, [node, yarn_js, "install"], qui..., ...)})
        File "/usr/local/home/iphy/.cache/bazel/_bazel_iphy/87c462f2b35b8d3dfe6f6c21308fd127/external/org_pubref_rules_node/node/internal/yarn_modules.bzl", line 4, in execute
                fail((" ".join(cmds) + ("failed: \nST...))))
/usr/local/home/iphy/.cache/bazel/_bazel_iphy/87c462f2b35b8d3dfe6f6c21308fd127/external/node/bin/node /usr/local/home/iphy/.cache/bazel/_bazel_iphy/87c462f2b35b8d3dfe6f6c21308fd127/external/yarn/bin/yarn.js installfailed:
STDOUT:
yarn install v1.0.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

STDERR:
warning package.json: No license field
warning js_toxcore_c_modules@1.0.0: No license field
error /usr/local/home/iphy/.cache/bazel/_bazel_iphy/87c462f2b35b8d3dfe6f6c21308fd127/external/js_toxcore_c_modules/node_modules/ref: Command failed.
Exit code: 127
Command: node-gyp rebuild
Arguments:
Directory: /usr/local/home/iphy/.cache/bazel/_bazel_iphy/87c462f2b35b8d3dfe6f6c21308fd127/external/js_toxcore_c_modules/node_modules/ref
Output:
/usr/bin/env: ‘sh’: No such file or directory
INFO: Elapsed time: 3.744s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by pcj** [comment]
Should be addressed by #60.
